version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: skinscan_db
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      # Menggunakan password baru sesuai request kamu
      MYSQL_ROOT_PASSWORD: "SkinScanDB"
      # Menggunakan nama database baru sesuai request kamu
      MYSQL_DATABASE: "skinscan-db"
    ports:
      - "3306:3306"
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    networks:
      - database_vpc # Ditempatkan di VPC Database sesuai standar PDF

  app:
    build: ./backend
    container_name: skinscan_app
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
    networks:
      - backend_vpc   # Masuk ke VPC Backend
      - database_vpc  # Jembatan khusus untuk mengakses kontainer DB

  frontend:
    image: nginx:alpine
    container_name: skinscan_frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./Frontend:/usr/share/nginx/html
    networks:
      - frontend_vpc  # Ditempatkan di VPC Frontend sesuai standar PDF

# =========================================================================
# SIMULASI ARSITEKTUR CLOUD (SEGMENTASI VPC SEPERTI KETENTUAN TUGAS)
# =========================================================================
networks:
  frontend_vpc:
    driver: bridge
  backend_vpc:
    driver: bridge
  database_vpc:
    driver: bridge

volumes:
  db_data: