-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.4.32-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             12.14.0.7170
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for skinscan_db
CREATE DATABASE IF NOT EXISTS `skinscan_db` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */;
USE `skinscan_db`;

-- Dumping structure for table skinscan_db.analysis_history
CREATE TABLE IF NOT EXISTS `analysis_history` (
  `analysis_id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `image_url` varchar(255) NOT NULL,
  `prediction_label` varchar(100) NOT NULL,
  `confidence_score` decimal(5,2) NOT NULL,
  `medical_description` text NOT NULL,
  `status` enum('pending','completed','failed') DEFAULT 'completed',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`analysis_id`),
  KEY `idx_user_analysis` (`user_id`),
  CONSTRAINT `fk_analysis_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table skinscan_db.analysis_history: ~18 rows (approximately)
INSERT INTO `analysis_history` (`analysis_id`, `user_id`, `image_url`, `prediction_label`, `confidence_score`, `medical_description`, `status`, `created_at`) VALUES
	(1, 1, 'uploads\\skin_1780913738261.webp', 'Eczema (Eksim) Ringan', 91.80, 'Berdasarkan analisis visual awal melalui algoritma citra digital, area kulit menunjukkan karakteristik dermatitis atopik atau eksim ringan. Terlihat pola inflamasi berupa kemerahan (eritema) disertai tekstur kulit yang cenderung kering dan bersisik halus.\n\nRekomendasi:\nGunakan pelembab hipoalergenik tanpa kandungan parfum sesegera mungkin setelah mandi.\nHindari membasuh area kulit yang meradang dengan air yang terlalu panas.\nGunakan sabun dengan formula lembut (pH seimbang) dan hindari menggaruk area yang gatal agar tidak memicu infeksi sekunder.\nSegera jadwalkan konsultasi dengan dokter spesialis kulit jika dalam waktu 3 hari kemerahan semakin meluas atau timbul rasa perih.', 'completed', '2026-06-08 10:15:40'),
	(2, 1, 'uploads\\skin_1780913749945.jfif', 'Eczema (Eksim) Ringan', 91.80, 'Berdasarkan analisis visual awal melalui algoritma citra digital, area kulit menunjukkan karakteristik dermatitis atopik atau eksim ringan. Terlihat pola inflamasi berupa kemerahan (eritema) disertai tekstur kulit yang cenderung kering dan bersisik halus.\n\nRekomendasi:\nGunakan pelembab hipoalergenik tanpa kandungan parfum sesegera mungkin setelah mandi.\nHindari membasuh area kulit yang meradang dengan air yang terlalu panas.\nGunakan sabun dengan formula lembut (pH seimbang) dan hindari menggaruk area yang gatal agar tidak memicu infeksi sekunder.\nSegera jadwalkan konsultasi dengan dokter spesialis kulit jika dalam waktu 3 hari kemerahan semakin meluas atau timbul rasa perih.', 'completed', '2026-06-08 10:15:52'),
	(3, 1, 'uploads\\skin_1780913772076.webp', 'Eczema (Eksim) Ringan', 91.80, 'Berdasarkan analisis visual awal melalui algoritma citra digital, area kulit menunjukkan karakteristik dermatitis atopik atau eksim ringan. Terlihat pola inflamasi berupa kemerahan (eritema) disertai tekstur kulit yang cenderung kering dan bersisik halus.\n\nRekomendasi:\nGunakan pelembab hipoalergenik tanpa kandungan parfum sesegera mungkin setelah mandi.\nHindari membasuh area kulit yang meradang dengan air yang terlalu panas.\nGunakan sabun dengan formula lembut (pH seimbang) dan hindari menggaruk area yang gatal agar tidak memicu infeksi sekunder.\nSegera jadwalkan konsultasi dengan dokter spesialis kulit jika dalam waktu 3 hari kemerahan semakin meluas atau timbul rasa perih.', 'completed', '2026-06-08 10:16:14'),
	(4, 1, 'uploads\\skin_1780914292820.webp', 'Kulit Sehat/Normal', 99.85, 'Berdasarkan analisis citra digital, kulit wajah menunjukkan karakteristik sehat dan normal. Tampak halus, bersih, tanpa tanda-tanda peradangan, lesi aktif, atau diskolorasi yang signifikan. Tekstur kulit terlihat merata dengan hidrasi yang optimal, mengindikasikan barrier kulit yang utuh dan fungsi kelenjar sebaceous yang seimbang. Tidak terdeteksi adanya indikasi kondisi dermatologis seperti jerawat, eksim, rosacea, atau hiperpigmentasi yang menonjol.\n\nRekomendasi:\n- Lanjutkan rutinitas perawatan kulit dasar yang konsisten (pembersih, pelembap, tabir surya).\n- Gunakan tabir surya spektrum luas dengan SPF minimal 30 setiap hari, bahkan saat mendung atau di dalam ruangan.\n- Jaga hidrasi tubuh dengan minum air yang cukup dan konsumsi makanan bergizi seimbang.\n- Hindari paparan sinar matahari berlebihan dan polusi untuk mencegah kerusakan kulit jangka panjang.\n- Rutin bersihkan wajah dua kali sehari untuk mengangkat kotoran dan sisa makeup, memastikan pori-pori tetap bersih.', 'completed', '2026-06-08 10:25:00'),
	(5, 1, 'uploads\\skin_1780914620283.jfif', 'Acne Vulgaris (Jerawat) Meradang', 89.50, 'Analisis visual mendeteksi adanya papula dan pustula inflamasi yang signifikan di area pipi dan rahang, karakteristik dari acne vulgaris tingkat sedang hingga berat dengan kemerahan di sekitar lesi.\n\nRekomendasi:\n- Bersihkan wajah dua kali sehari menggunakan sabun berbahan lembut (gentle cleanser).\n- Hindari memencet atau menyentuh jerawat secara langsung untuk mencegah bekas luka bopeng (scarring).\n- Gunakan gel totol jerawat yang mengandung Salicylic Acid atau Benzoyl Peroxide.\n- Gunakan tabir surya non-comedogenic setiap hari untuk mencegah hiperpigmentasi pasca-inflamasi.', 'completed', '2026-06-08 10:30:22'),
	(6, 1, 'uploads\\skin_1780914635994.webp', 'Kulit Sehat', 99.85, 'Algoritma visual citra digital tidak mendeteksi adanya tanda-tanda penyakit kulit, inflamasi, lesi, atau kelainan dermatologis lainnya pada gambar yang dilampirkan. Kulit tampak bersih, halus, terhidrasi dengan baik, dan memiliki warna kulit yang merata dengan kilau alami yang sehat, menunjukkan kondisi kulit yang optimal.\n\nRekomendasi:\n- Lanjutkan rutinitas perawatan kulit yang konsisten sesuai dengan jenis kulit Anda.\n- Gunakan tabir surya (minimal SPF 30) setiap hari, bahkan saat cuaca mendung atau di dalam ruangan, untuk melindungi kulit dari kerusakan akibat sinar UV.\n- Pastikan asupan cairan yang cukup dan konsumsi diet seimbang yang kaya antioksidan untuk mendukung kesehatan kulit dari dalam.\n- Bersihkan wajah secara lembut dua kali sehari dan hindari menyentuh wajah terlalu sering dengan tangan yang belum dicuci untuk mencegah kontaminasi.', 'completed', '2026-06-08 10:30:43'),
	(7, 1, 'uploads\\skin_1780914689482.jpg', 'Acne Vulgaris (Jerawat) Meradang', 89.50, 'Analisis visual mendeteksi adanya papula dan pustula inflamasi yang signifikan di area pipi dan rahang, karakteristik dari acne vulgaris tingkat sedang hingga berat dengan kemerahan di sekitar lesi.\n\nRekomendasi:\n- Bersihkan wajah dua kali sehari menggunakan sabun berbahan lembut (gentle cleanser).\n- Hindari memencet atau menyentuh jerawat secara langsung untuk mencegah bekas luka bopeng (scarring).\n- Gunakan gel totol jerawat yang mengandung Salicylic Acid atau Benzoyl Peroxide.\n- Gunakan tabir surya non-comedogenic setiap hari untuk mencegah hiperpigmentasi pasca-inflamasi.', 'completed', '2026-06-08 10:31:32'),
	(8, 1, 'uploads\\skin_1780914781751.webp', 'Hiperpigmentasi Pasca Inflamasi Akibat Toksisitas Merkuri', 95.50, 'Berdasarkan analisis citra digital, area wajah menunjukkan hiperpigmentasi difus yang parah, terutama pada pipi, dahi, dan area perioral, dengan warna kulit yang tampak menggelap secara tidak merata dan adanya kemerahan di beberapa bagian. Kondisi ini sangat konsisten dengan efek samping jangka panjang dari penggunaan produk yang mengandung merkuri. Merkuri dapat menyebabkan iritasi kulit, kerusakan sel melanosit, dan stimulasi produksi melanin berlebihan, yang kemudian memicu hiperpigmentasi pasca-inflamasi (PIH) yang persisten dan seringkali sulit diatasi. Efek ini dapat muncul beberapa bulan hingga tahun setelah penghentian penggunaan produk merkuri, diperparah oleh paparan sinar UV. Kulit juga tampak rentan terhadap sensitivitas dan mungkin menunjukkan tekstur yang tidak rata.\n\nRekomendasi:\n- Segera hentikan penggunaan semua produk perawatan kulit yang tidak jelas komposisinya atau dicurigai mengandung merkuri, hydroquinone, atau steroid tanpa resep dokter.\n- Gunakan tabir surya spektrum luas dengan SPF minimal 30 atau lebih tinggi setiap hari, dan ulangi aplikasi setiap 2-3 jam, terutama saat beraktivitas di luar ruangan.\n- Lindungi kulit dari paparan sinar matahari langsung dengan menggunakan topi lebar, kacamata hitam, dan pakaian pelindung, serta sebisa mungkin hindari berjemur.\n- Jaga kelembapan kulit dengan menggunakan pelembap yang lembut, non-komedogenik, dan bebas pewangi untuk membantu memperbaiki barrier kulit yang rusak dan mengurangi iritasi.', 'completed', '2026-06-08 10:33:13'),
	(9, 1, 'uploads\\skin_1780914929638.webp', 'Kulit Kering Parah (Xerosis Berat)', 98.75, 'Analisis citra digital menunjukkan kondisi kulit wajah yang mengalami dehidrasi ekstrim dan kerusakan sawar kulit. Terlihat jelas pola kulit pecah-pecah (fissures) yang dalam dan luas, serta tekstur bersisik yang signifikan di seluruh area wajah. Kondisi ini mengindikasikan xerosis berat atau kulit kering yang sangat parah, di mana lapisan pelindung kulit (stratum korneum) kehilangan kemampuan untuk mempertahankan kelembapan secara efektif, menyebabkan kulit menjadi kasar, rapuh, dan rentan terhadap iritasi. Penampakan visual ini konsisten dengan kekurangan kadar air yang drastis di epidermis.\n\nRekomendasi:\n- Gunakan pelembap yang kaya dan oklusif (mengandung ceramide, asam hialuronat, petrolatum, shea butter) segera setelah mandi, saat kulit masih sedikit lembap, minimal dua kali sehari.\n- Mandi atau cuci muka dengan air hangat (bukan panas) dan batasi durasi mandi tidak lebih dari 5-10 menit. Gunakan sabun pembersih yang lembut, bebas pewangi, dan hipoalergenik.\n- Hindari produk perawatan kulit yang mengandung alkohol, pewangi kuat, astringent, atau bahan iritatif lainnya yang dapat memperparah kekeringan dan mengganggu sawar kulit.\n- Pertimbangkan penggunaan humidifier di dalam ruangan, terutama saat tidur atau di lingkungan kering, untuk menjaga kelembapan udara. Pastikan asupan cairan tubuh tercukupi dengan minum air yang cukup sepanjang hari.', 'completed', '2026-06-08 10:35:37'),
	(10, 1, 'uploads\\skin_1780919183983.webp', 'Acne Vulgaris (Jerawat) Meradang', 89.50, 'Analisis visual mendeteksi adanya papula dan pustula inflamasi yang signifikan di area pipi dan rahang, karakteristik dari acne vulgaris tingkat sedang hingga berat dengan kemerahan di sekitar lesi.\n\nRekomendasi:\n- Bersihkan wajah dua kali sehari menggunakan sabun berbahan lembut (gentle cleanser).\n- Hindari memencet atau menyentuh jerawat secara langsung untuk mencegah bekas luka bopeng (scarring).\n- Gunakan gel totol jerawat yang mengandung Salicylic Acid atau Benzoyl Peroxide.\n- Gunakan tabir surya non-comedogenic setiap hari untuk mencegah hiperpigmentasi pasca-inflamasi.', 'completed', '2026-06-08 11:46:27'),
	(11, 1, 'uploads\\skin_1780919270525.webp', 'Hiperpigmentasi Pasca-Inflamasi Berat dan Potensi Ochronosis Eksogen', 95.00, 'Berdasarkan analisis citra digital, tampak adanya hiperpigmentasi difus dan berat pada wajah, ditandai dengan bercak-bercak gelap hingga kehitaman yang tidak merata, terutama di area pipi, dahi, dan dagu. Terdapat juga kemerahan yang mendasari di beberapa area, menunjukkan adanya proses inflamasi kronis pada kulit. Informasi tambahan yang tertera pada gambar mengenai riwayat penggunaan produk merkuri dan efek \'gosong\' serta \'flek hitam\' yang muncul setelah penghentian sangat mendukung diagnosis ini. Paparan merkuri pada kulit dapat menyebabkan iritasi parah, kerusakan sel melanosit, dan seringkali diikuti dengan hiperpigmentasi pasca-inflamasi (Post-Inflammatory Hyperpigmentation/PIH) yang sulit diatasi. Dalam kasus yang parah dan kronis, penggunaan merkuri juga dapat memicu Ochronosis Eksogen, suatu kondisi di mana terjadi deposisi pigmen kebiruan atau kehitaman di dermis, yang memperburuk diskolorasi kulit secara signifikan. Kondisi ini menunjukkan kerusakan kulit yang serius dan memerlukan penanganan medis yang tepat dan terarah.\n\nRekomendasi:\n- Sangat disarankan untuk segera berkonsultasi dengan Dokter Spesialis Kulit (Dermatolog) untuk mendapatkan diagnosis pasti, evaluasi menyeluruh, dan rencana penanganan yang komprehensif. Ini adalah kondisi serius yang membutuhkan intervensi profesional.\n- Hentikan segera penggunaan semua produk perawatan kulit yang tidak direkomendasikan oleh Dokter Spesialis Kulit, terutama produk yang tidak jelas kandungannya atau dicurigai mengandung zat berbahaya seperti merkuri.\n- Gunakan tabir surya spektrum luas (minimal SPF 30 dan PA+++) setiap hari, bahkan saat berada di dalam ruangan, dan ulangi aplikasi setiap 2-3 jam jika beraktivitas di luar ruangan. Perlindungan matahari sangat krusial untuk mencegah penggelapan lebih lanjut dan membantu proses pemulihan.\n- Jaga kelembapan kulit dengan pelembap yang lembut, non-komedogenik, dan bebas pewangi untuk membantu memulihkan fungsi sawar kulit yang rusak dan mengurangi iritasi.\n- Hindari paparan sinar matahari langsung, terutama pada jam puncak (pukul 10 pagi hingga 4 sore). Gunakan pelindung fisik seperti topi lebar dan kacamata hitam saat berada di luar ruangan.\n- Jangan mencoba mengatasi hiperpigmentasi ini dengan produk pencerah kulit bebas yang dijual di pasaran tanpa pengawasan medis, karena dapat memperburuk kondisi, menyebabkan reaksi alergi, atau efek samping yang tidak diinginkan.', 'completed', '2026-06-08 11:48:05'),
	(12, 1, 'uploads\\skin_1780919300518.webp', 'Hiperpigmentasi Pasca Penggunaan Merkuri dan Dermatitis Kontak Iritan', 95.00, 'Analisis citra digital menunjukkan hiperpigmentasi difus dan berat pada wajah, dengan area yang tampak menghitam (cokelat gelap hingga keabu-abuan) secara tidak merata, terutama di daerah pipi, dahi, dan sekitar mulut. Terdapat juga tanda-tanda eritema (kemerahan) dan inflamasi, menunjukkan adanya dermatitis kontak iritan yang kemungkinan dipicu oleh penghentian zat tertentu atau reaksi terhadap kerusakan kulit sebelumnya. Tekstur kulit tampak tidak merata dengan beberapa flek-flek yang lebih gelap. Kondisi ini sangat konsisten dengan efek samping jangka panjang dan \'rebound effect\' dari penggunaan produk pemutih kulit yang mengandung merkuri, yang dapat menyebabkan exogenous ochronosis, post-inflammatory hyperpigmentation yang parah, dan sensitivitas kulit yang meningkat.\n\nRekomendasi:\n- Segera konsultasikan dengan Dokter Spesialis Kulit untuk diagnosis dan rencana perawatan yang komprehensif. Kondisi ini memerlukan penanganan medis profesional.\n- Hentikan penggunaan semua produk pencerah kulit yang tidak memiliki izin edar atau tidak jelas kandungannya, terutama yang dicurigai mengandung merkuri atau bahan berbahaya lainnya.\n- Lindungi kulit dari paparan sinar matahari secara ketat dengan menggunakan tabir surya spektrum luas (minimal SPF 30) setiap hari, bahkan di dalam ruangan, dan gunakan perlindungan fisik seperti topi lebar atau payung saat beraktivitas di luar.\n- Gunakan pelembap yang lembut, bebas pewangi, dan hipoalergenik untuk membantu menenangkan kulit yang teriritasi dan mendukung perbaikan barier kulit yang rusak.', 'completed', '2026-06-08 11:48:29'),
	(13, 1, 'uploads\\skin_1780919315730.webp', 'Acne Vulgaris (Jerawat) Meradang', 89.50, 'Analisis visual mendeteksi adanya papula dan pustula inflamasi yang signifikan di area pipi dan rahang, karakteristik dari acne vulgaris tingkat sedang hingga berat dengan kemerahan di sekitar lesi.\n\nRekomendasi:\n- Bersihkan wajah dua kali sehari menggunakan sabun berbahan lembut (gentle cleanser).\n- Hindari memencet atau menyentuh jerawat secara langsung untuk mencegah bekas luka bopeng (scarring).\n- Gunakan gel totol jerawat yang mengandung Salicylic Acid atau Benzoyl Peroxide.\n- Gunakan tabir surya non-comedogenic setiap hari untuk mencegah hiperpigmentasi pasca-inflamasi.', 'completed', '2026-06-08 11:48:37'),
	(14, 1, 'uploads\\skin_1780919679089.webp', 'Kulit Kering Parah (Xerosis Berat)', 95.00, 'Kulit Kering Parah, atau dikenal juga sebagai Xerosis Berat, adalah kondisi di mana kulit kehilangan kelembaban esensialnya secara signifikan, menyebabkan lapisan pelindung kulit (skin barrier) menjadi terganggu. Hal ini mengakibatkan kulit terasa kasar, bersisik, pecah-pecah, gatal, dan bahkan dapat menimbulkan iritasi atau peradangan. Faktor penyebab bisa meliputi cuaca ekstrem (dingin atau panas yang kering), paparan bahan kimia keras, mandi air panas terlalu lama, penggunaan sabun yang mengikis minyak alami kulit, kondisi medis tertentu seperti dermatitis atopik atau hipotiroidisme, serta penuaan. Pada kasus yang parah seperti gambar ini, celah pada kulit bisa menjadi jalan masuk bagi bakteri dan alergen, meningkatkan risiko infeksi atau reaksi alergi.\n\nRekomendasi:\n- Gunakan pelembab secara rutin dan liberal, terutama setelah mandi, saat kulit masih sedikit lembab. Pilih pelembab dengan kandungan emolien (seperti ceramide, asam hialuronat, gliserin) yang tinggi dan bebas pewangi.\n- Mandi dengan air hangat (bukan panas) dan batasi durasi mandi. Gunakan sabun pembersih yang lembut, bebas sulfat, dan memiliki pH seimbang, atau pembersih berbasis minyak.\n- Hindari menggosok kulit terlalu keras atau menggunakan spons mandi yang kasar. Setelah mandi, tepuk-tepuk kulit hingga kering, jangan digosok, untuk mempertahankan kelembaban.\n- Jaga hidrasi tubuh dengan minum air yang cukup sepanjang hari. Pertimbangkan untuk menggunakan humidifier di rumah, terutama jika tinggal di lingkungan yang kering.', 'completed', '2026-06-08 11:54:45'),
	(15, 1, 'uploads\\skin_1780919696363.webp', 'Hiperpigmentasi Pasca-Inflamasi Parah dan Ochronosis Eksogen (Diduga Akibat Merkuri)', 90.00, 'Kondisi kulit yang terlihat menunjukkan hiperpigmentasi yang sangat parah, menyebar luas di area wajah, dengan warna kehitaman yang intens, beberapa area tampak kebiruan atau keabu-abuan. Ini sangat konsisten dengan diagnosis Hiperpigmentasi Pasca-Inflamasi (HPI) yang berat dan kemungkinan besar Ochronosis Eksogen. Riwayat penggunaan produk bermerkuri dan penghentiannya sangat mendukung diagnosis ini. Merkuri adalah zat berbahaya yang dapat merusak melanosit (sel penghasil pigmen) dan menyebabkan disregulasi produksi melanin. Setelah penghentian, kulit sering mengalami \'rebound\' dengan pigmentasi yang jauh lebih gelap dan lebih sulit diobati, bahkan dapat memicu reaksi peradangan kronis yang menyebabkan perubahan warna permanen seperti ochronosis, yaitu deposisi pigmen di lapisan dermis kulit. Kondisi ini memerlukan penanganan medis yang serius dan terstruktur dari Dokter Spesialis Kulit.\n\nRekomendasi:\n- Segera konsultasi dengan Dokter Spesialis Kulit untuk diagnosis akurat dan rencana perawatan yang komprehensif. Penanganan kondisi ini membutuhkan terapi medis spesifik.\n- Proteksi matahari maksimal: Gunakan tabir surya spektrum luas dengan SPF minimal 30 setiap hari (ulang setiap 2-3 jam), lengkapi dengan topi lebar dan hindari paparan sinar matahari langsung, terutama pada jam-jam puncak.\n- Hentikan total penggunaan produk perawatan kulit yang tidak jelas, tidak terdaftar BPOM, atau diduga mengandung bahan berbahaya seperti merkuri. Beralih ke produk yang diformulasikan lembut, hipoalergenik, dan bebas pewangi.\n- Fokus pada hidrasi dan perbaikan sawar kulit: Gunakan pembersih wajah yang lembut dan pelembap intensif yang mengandung ceramide atau asam hialuronat untuk membantu menenangkan kulit, mengurangi iritasi, dan memperbaiki lapisan pelindung kulit.', 'completed', '2026-06-08 11:55:08'),
	(16, 1, 'uploads\\skin_1780919738439.jpg', 'Acne Vulgaris (Jerawat) Meradang', 89.50, 'Analisis visual mendeteksi adanya papula dan pustula inflamasi yang signifikan di area pipi dan rahang, karakteristik dari acne vulgaris tingkat sedang hingga berat dengan kemerahan di sekitar lesi.\n\nRekomendasi:\n- Bersihkan wajah dua kali sehari menggunakan sabun berbahan lembut (gentle cleanser).\n- Hindari memencet atau menyentuh jerawat secara langsung untuk mencegah bekas luka bopeng (scarring).\n- Gunakan gel totol jerawat yang mengandung Salicylic Acid atau Benzoyl Peroxide.\n- Gunakan tabir surya non-comedogenic setiap hari untuk mencegah hiperpigmentasi pasca-inflamasi.', 'completed', '2026-06-08 11:55:42'),
	(17, 1, 'uploads\\skin_1780919755677.webp', 'Kulit Sehat', 99.90, 'Berdasarkan analisis citra, kulit Anda menunjukkan karakteristik yang sehat. Tidak ditemukan adanya tanda-tanda peradangan, ruam, lesi, atau kelainan kulit lainnya yang mengindikasikan penyakit tertentu. Tekstur kulit tampak halus, warna kulit merata, dan secara keseluruhan menunjukkan hidrasi yang baik serta vitalitas kulit yang optimal.\n\nRekomendasi:\n- Tetap jaga hidrasi kulit dengan minum air yang cukup dan menggunakan pelembap secara rutin.\n- Lindungi kulit dari paparan sinar matahari langsung dengan menggunakan tabir surya minimal SPF 30 setiap hari, bahkan saat mendung.\n- Bersihkan wajah dua kali sehari dengan pembersih yang lembut untuk menghilangkan kotoran dan riasan tanpa mengiritasi kulit.\n- Terapkan pola makan sehat dan seimbang yang kaya antioksidan serta vitamin untuk mendukung kesehatan kulit dari dalam.', 'completed', '2026-06-08 11:56:04'),
	(18, 1, 'uploads\\skin_1780919802720.webp', 'Jerawat Parah/Acne Vulgaris Berat', 95.50, 'Kondisi kulit ini menunjukkan Jerawat Vulgaris dalam kategori berat, ditandai dengan adanya banyak lesi inflamasi seperti papula, pustula, nodul, dan bahkan kista. Lesi-lesi ini seringkali berukuran besar, terasa nyeri, dan terletak lebih dalam di bawah permukaan kulit. Jerawat parah terjadi akibat kombinasi produksi minyak berlebih (sebum), penyumbatan folikel rambut oleh sel kulit mati, pertumbuhan bakteri Propionibacterium acnes, dan respons inflamasi tubuh yang kuat. Tanpa penanganan yang tepat, jerawat parah dapat menyebabkan jaringan parut permanen dan hiperpigmentasi pasca-inflamasi (bekas kehitaman atau kemerahan).\n\nRekomendasi:\n- Bersihkan wajah dua kali sehari dengan pembersih yang lembut dan tidak mengiritasi, menggunakan air hangat.\n- Hindari memencet, menggaruk, atau memanipulasi jerawat karena dapat memperburuk peradangan, menyebarkan bakteri, dan meningkatkan risiko bekas luka.\n- Gunakan produk perawatan kulit yang berlabel \'non-komedogenik\' (tidak menyumbat pori) dan \'oil-free\' untuk mencegah penumpukan minyak dan sel kulit mati.\n- Segera konsultasikan dengan dokter spesialis kulit untuk evaluasi dan penanganan yang lebih intensif, seperti terapi obat oral (antibiotik, isotretinoin) atau topikal (retinoid, asam salisilat) yang mungkin diperlukan.', 'completed', '2026-06-08 11:56:54');

-- Dumping structure for table skinscan_db.recommendations
CREATE TABLE IF NOT EXISTS `recommendations` (
  `recommendation_id` int(11) NOT NULL AUTO_INCREMENT,
  `analysis_id` int(11) NOT NULL,
  `recommendation_text` text NOT NULL,
  PRIMARY KEY (`recommendation_id`),
  KEY `fk_recommendation_analysis` (`analysis_id`),
  CONSTRAINT `fk_recommendation_analysis` FOREIGN KEY (`analysis_id`) REFERENCES `analysis_history` (`analysis_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table skinscan_db.recommendations: ~0 rows (approximately)

-- Dumping structure for table skinscan_db.users
CREATE TABLE IF NOT EXISTS `users` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table skinscan_db.users: ~1 rows (approximately)
INSERT INTO `users` (`user_id`, `name`, `email`, `password_hash`, `created_at`, `updated_at`) VALUES
	(1, 'Nazwa Nur', 'nazwa@example.com', '$2b$10$xyz123hashedpasswordexample', '2026-06-08 09:26:32', '2026-06-08 09:26:32');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
